### ISSUE TITLE
Wrong URL created for image in map - wrong category used

### ISSUE THREAD

**Issue by IT-Sumpfling** [xbgmsharp/piwigo-openstreetmap#108]
Hi,
the issue in #74 is still open. Seems like the order of merges was mixed up - ending WITHOUT the fix on main ...
https://github.com/xbgmsharp/piwigo-openstreetmap/commits/master/include/functions_map.php

https://github.com/xbgmsharp/piwigo-openstreetmap/blame/master/include/functions_map.php#L207

**Comment by xbgmsharp** [comment]
The latest code and the path match:
https://github.com/xbgmsharp/piwigo-openstreetmap/blob/master/include/functions_map.php#L207
https://github.com/xbgmsharp/piwigo-openstreetmap/commit/40ead0621fe4f09ac7b1eb4b470ce874ef82ae48

Or are you saying it should ``ic.category_id`` instead of ``i.storage_category_id``.
When confirm I can update the code accordingly.

Thanks

**Comment by IT-Sumpfling** [comment]
Hi,

**yes**, according to ThomasDaheim in [#74](https://github.com/xbgmsharp/piwigo-openstreetmap/issues/74#issuecomment-159026104) and my own tests (I had the problem described there and changed my local code accordingly) **it should be ic.category_id** .

**Comment by xbgmsharp** [comment]
Thanks,  Fix commited.

**Comment by IT-Sumpfling** [comment]
Small typo in your fix - you wrote i.category_id instead of i**c**.category_id
Thanks for the quick reactions!

**Comment by xbgmsharp** [comment]
Oups sorry, done.
