### ISSUE TITLE
Feature request: Ability to export location coordinates to original file/picture

### ISSUE THREAD

**Issue by Saur0o0n** [xbgmsharp/piwigo-openstreetmap#155]
Hi,
Since a lot of my older pictures (and quite a lot of new one - from old camera) does not have location coordinates I set, for some of them, it manually. It's not an issue now, but in future when perhaps I'll need to move pictures or do some changes all this manual work will be lost.
It would be great to export manually provided coordinates to original picture file. I see it could be done directly (just modify file) or with generated shell script (for manual, external usage).
Any chance for this feature?

**Comment by jheinitz** [comment]
Hello!

There is a plugin called "Write Metadata". Unfortunatly this does not
support the writing of GPS coordinates yet, I did change the code and it
works for me because I have the same problem with a lot of old pictures or
scanned pictures. I already asked plegall to include my changes, but he has
not changed the code yet.

See here for more details: https://github.com/plegall/Piwigo-write_metadata


Best regards

Jens

2018-05-19 13:03 GMT+02:00 Sauron <notifications@github.com>:

**Comment by 7tonin** [comment]
Could you fork piwigo-write_metadata and publish your changes as a patch ?
It will then be available for reviewers and maybe merged.

**Comment by xbgmsharp** [comment]
You can export location coordinates using ffprobe or exiftool.
exiftool:
`exiftool -struct -n -json image.jpg`
ffprobe:
`ffprobe -hide_banner -loglevel fatal -show_error -show_format -show_streams -show_programs -show_chapters -show_private_data -print_format json image.jpg`
